Added new regulator and mux
UWARG/WARG-KiCAD pull request #17
Opened 2018-06-05 17:49 UTC by heyitslu

Added TPS54308 (Buck reg) and ICL7673 (Power mux) to KiCad library and spreadsheet.

2018-06-05 22:18 UTC, scholvat requested changes
Few comments on library stuff, rest of the comments on the main PR.

2018-06-05 22:18 UTC, scholvat commented on WARG-kicad.pretty/1.7 x 6.5.kicad_mod
> -(module "1.7 x 6.5" (layer F.Cu) (tedit 592667CC)
Make sure not to be removing these files, even if they aren't being used in the current schematic. This may have occured due to an out of date branch of WARG-kicad

2018-06-05 22:18 UTC, scholvat commented on WARG-kicad.pretty/sloth.kicad_mod
> -(module sloth (layer F.Cu) (tedit 0)
Don't remove my beautiful sloth :'(

2018-06-05 22:18 UTC, scholvat commented on component_library.csv
> +MUX,Digi-Key,ICL7673CPAZ-ND,IC OR CTRLR SRC SELECT 8DIP,,0,no,
typo- it should be MUX-001

2018-06-19 18:13 UTC, eterrestrial commented on component_library.csv
> +CAPP-014,Digi-Key,478-5778-1-ND,CAP CER 0.1UF 50V X7R 0603,AVX Corporation,0,18-06-2018,
22uF and 0.1uF capacitors already exist, idk if there was a specific reason you added CAPP-012 and CAPP-014 but it looks like you never use CAPP-012 anyways.

2018-06-19 18:51 UTC, eterrestrial reviewed
Like Stephen said, a lot of the components are missing from the WARG footprint library. I don't know if that's something you're gonna have to fix or if it'll get fixed in the merge.

2018-06-19 18:51 UTC, eterrestrial commented on WARG-kicad.pretty/LMZ21701SILT.kicad_mod
> +  (fp_text reference U15 (at 0 3.81) (layer F.SilkS)
Can't find a schematic for this footprint, also I don't think the reference field should be anything other than REF**, not U15. This component is also not in the csv, or at least there's no reference of "LMZ21701SILT".

2018-06-24 15:52 UTC, heyitslu commented on WARG-kicad.pretty/sloth.kicad_mod
> -(module sloth (layer F.Cu) (tedit 0)
Oh these comments I am sorry :(

2018-06-24 16:19 UTC, scholvat requested changes

2018-06-24 16:19 UTC, scholvat commented on .gitignore
> +<<<<<<< HEAD
Merge conflict here needs to be resolved

2018-06-24 16:19 UTC, scholvat commented on .gitmodules
> +[submodule "WARG-kicad"]
Not sure why this is here...

2018-06-24 16:19 UTC, scholvat commented on README.md
> -
Why are these changes needed?

2018-06-24 16:19 UTC, scholvat commented on WARG-kicad.pretty/TSOT-23-6_MK06A_HandSoldering.kicad_mod
> -(module TSOT-23-6_MK06A_HandSoldering (layer F.Cu) (tedit 592B451F)
Why is this getting removed?

2018-06-26 00:41 UTC, merged